ProductsAccountingNew/Controllers/ProductPricesController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProductsAccountingNew.Models;
using ProductsAccountingNew.Services;

namespace ProductsAccountingNew.Controllers
{
    [Authorize]
    public class ProductPricesController : Controller
    {
        private readonly ILogger<ProductPricesController> _logger;
        private readonly IProductPricesService _productPriceService;

        public ProductPricesController(ILogger<ProductPricesController> logger, IProductPricesService productPriceService)
        {
            _logger = logger;
            _productPriceService = productPriceService;
        }


        public ActionResult Index()
        {
            var productsWithPrice = _productPriceService.GetProductWithPrice();
            ViewBag.ProductPrices = productsWithPrice;
            return View();
        }

        [HttpPost]
        public IActionResult ProductPrices(ProductPrice productPrice)
        {
            _productPriceService.AddProductWithPrice(productPrice);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("/change_price/{id}")]
        public new IActionResult ProductPrice(Guid id)
        {
            var productWithPrice = _productPriceService.GetProductWithPrice().FirstOrDefault(x => x.Id == id);
            return View(productWithPrice);
        }

        [HttpPost("/change_price")]
        public IActionResult Edit(ProductPrice productWithPrice)
        {
            _productPriceService.UpdatePrice(productWithPrice);
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete("/delete_price/{id}")]
        public IActionResult Delete(Guid id)
        {
            _productPriceService.DeleteProductWithPrice(id);
            return Ok();
        }
    }
}

ProductsAccountingNew/Controllers/ProductsOfUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProductsAccountingNew.Models;
using ProductsAccountingNew.Services;
using System;

namespace ProductsAccountingNew.Controllers
{
    [Authorize]
    public class ProductsOfUsersController : Controller
    {
        private readonly ILogger<ProductsOfUsersController> _logger;
        private readonly IProductsOfUsersService _productsService;
        public ProductsOfUsersController(ILogger<ProductsOfUsersController> logger, IProductsOfUsersService productsService)
        {
            _logger = logger;
            _productsService = productsService;
        }

        public IActionResult Index()
        {
            string nameOfCurrentUser = User.Identity.Name;

            var products = _productsService.GetProducts(nameOfCurrentUser);
            ViewBag.ProductsOfUsers = products;
            return View();
        }

        [HttpPost]
        public IActionResult ProductsOfUsers(ProductOfUser productOfUser)
        {
            string nameOfCurrentUser = User.Identity.Name;

            _productsService.AddProductToUser(nameOfCurrentUser, productOfUser);
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete("/delete_product/{id}")]
        public IActionResult Delete(Guid id, Guid userId)
        {
            _productsService.DeleteProduct(id, userId);
            return Ok();
        }

    }
}

ProductsAccountingNew/Controllers/ShoppingListController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using ProductsAccountingNew.Models;
using ProductsAccountingNew.Services;
using System;

namespace ProductsAccountingNew.Controllers
{
    [Authorize]
    public class ShoppingListController : Controller
    {
        private readonly ILogger<ShoppingListController> _logger;
        private readonly IShoppingListService _shoppingListService;

        public ShoppingListController(ILogger<ShoppingListController> logger, IShoppingListService shoppingListService)
        {
            _logger = logger;
            _shoppingListService = shoppingListService;
        }

        public IActionResult Index()
        {
            string userName = User.Identity.Name;

            var shoppingList = _shoppingListService.GetShoppingList(userName);
            ViewBag.ShoppingList = shoppingList;

            ViewBag.Balance = _shoppingListService.GetBalance(userName);

            var productNamesAndPrices = _shoppingListService.GetProductNamesAndPrices();

            ViewBag.ProductNames = new SelectList(productNamesAndPrices, "Name");


            return View();
        }

        [HttpPost]
        public IActionResult ShoppingList(ShoppingList shoppingList)
        {
            string userName = User.Identity.Name;
            _shoppingListService.AddProduct(userName, shoppingList.Name, shoppingList.Count);

            return RedirectToAction(nameof(Index));
        }


        [HttpPost("/shopping_list/buy_product/{productId}/{productName}/{count}/{price}")]
        public IActionResult BuyProduct(Guid productId, string productName, int count, int price)
        {
            string userName = User.Identity.Name;

            _shoppingListService.BuyProduct(userName, productId, productName, count, price);

            return Ok();
        }


        [HttpDelete("/shopping_list/delete_product/{productName}")]
        public IActionResult DeleteProduct(string productName)
        {
            string userName = User.Identity.Name;

            _shoppingListService.DeleteProduct(userName, productName);
            return Ok();
        }
    }
}

ProductsAccountingNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>

<style>

     a {
        color: #212529;
    }

    a.navbar-brand, a.nav-link {
        color: white;
    }

        a:hover, a:focus {
            color: #ffc107
        }

    .dropdown-toggle:hover, .dropdown-toggle:focus {
        color: #ffc107;
    }

    nav {
        background-color: #343a40;
    }
</style>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex ">


                    @if (User.Identity.Name == "admin")
                    {
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="navbar-brand main" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link users" asp-area="" asp-controller="Users" asp-action="Index">Пользователи</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link prices" asp-area="" asp-controller="ProductPrices" asp-action="Index">Цены на продукты</a>
                            </li>

                        </ul>

                    }

                    else if (User.Identity.Name != "" && User.Identity.Name != null)
                    {

                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="navbar-brand main" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link  products" asp-area="" asp-controller="ProductsOfUsers" asp-action="Index">Мои продукты</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link  shoppingList" asp-area="" asp-controller="ShoppingList" asp-action="Index">Корзина</a>
                            </li>

                        </ul>

                    }

                    else
                    {
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="navbar-brand main" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                        aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                            </li>
                        </ul>

                    }


                    <ul class="navbar-nav navbar-right flex-grow-1">

                        <li class="dropdown nav-item" style="margin-left: auto; padding-right: 90px;">
                            <a href="#" class="dropdown-toggle nav-link" id="menu-login" data-toggle="dropdown">Вход<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><h6><a class="nav-link" id="login-link" asp-area="" asp-controller="Authentication" asp-action="Index" style="color: #343a40;">Вход</a></h6></li>
                                <li><h6><a class="nav-link" id="register-menu" asp-area="" asp-controller="Authentication" asp-action="RegisterPage" style="color: #343a40;">Регистрация</a></h6></li>
                                <li><h6><a class="nav-link" id="logout-menu" asp-area="" asp-controller="Authentication" asp-action="Logout" style="color: #343a40;">Выйти</a></h6></li>
                            </ul>
                        </li>
                    </ul>



                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Разработчик: Самойлов
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <script type="text/javascript">
        $.ajax({
            url: '/authenticated',
            type: 'GET',
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                document.getElementById("menu-login").innerText = "Меню";
                document.getElementById("login-link").style.display = "none";
                document.getElementById("logout-menu").style.display = "block";
                document.getElementById("register-menu").style.display = "none";
            },

            error: function () {
                document.getElementById("menu-login").innerText = "Войти";
                document.getElementById("login-link").innerText = "Вход";
                document.getElementById("logout-menu").style.display = "none";
                document.getElementById("register-menu").style.display = "block";
            }
        })
    </script>

</body>
</html>